### PR TITLE
Convert lakeFetch from sp/rgeos to sf

### PR DESCRIPTION
**Pull request by jsta**
I converted `lakeFetch` from sp/rgeos to sf (#18). 

Getting different results on the example code, not sure why:
sp/rgeos == 3753.523
sf == 3520.583 [m]

I replaced:
rgeos::gIntersection 	with 	sf::st_intersection
rgeos::gWithin 		with 	sf::st_within
rgeos::gLength 		with 	sf::st_length

### CODE REVIEW

**Comment by jsta** [comment]
This should give an idea/blueprint of what it would take to convert the entire package.

**Comment by jhollist** [comment]
Thanks for working on this.  I'll try to carve out some time this next week to look into why the different results.  I can't remember if there is a sampling bit to lake fetch or not.  If so, that would explain it.    Have you tried running both with the same random seed?

Thanks again, and Happy New Year, Jemma!

**Comment by jhollist** [comment]
Got a chance to look at this today.  Main reason for the difference was the original version used coordinates on a SpatialPolygonsDataFrame which returns a single XY for the location of the label point.  It is approximately the centroid (~ line 77) .  Your version has it return all the coordinates, not the centroid, and thus the fetch lines that are tested are slightly different than in the original. I have a version working with this change in it.  I also was able to speed up the section that pulls out the individual segments and recombined with do.call (~lines 117-127).  A couple of st_casts will do the same thing.

I will merge this PR and then will push my changes to it directly to jhollist/lakemorpho.

Thanks again for starting this process, @jsta!

**Comment by jhollist** [comment]
Plus, the CRAN version has a bug in it, which this fixes!  The CRAN one returns a line that crosses shoreline...  May push this change to CRAN sooner rather than later.

**Pull request merged**
